vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO MAIPA01/pcre2cpp
    REF "v${VERSION}"
    SHA512 32e468b020ed15bd41c08c6b7486573afa09ff43252449411b40a9c1d3102ccb94bcfe766cf2de8adbadf620b05b919296d06c610abf460bfdb0727749e7f6a4
    HEAD_REF main
    PATCHES
        fix-pcre2-targets-and-consumer-interface.patch
)

set(VCPKG_BUILD_TYPE release) # header only library

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DPCRE2CPP_MSTD_EXTERNAL=ON
        -DPCRE2CPP_PCRE2_EXTERNAL=ON
        -DPCRE2CPP_BUILD_TESTS=OFF
        -DPCRE2CPP_BUILD_BENCHMARK=OFF
        -DPCRE2CPP_BUILD_COVERAGE=OFF
        -DPCRE2CPP_BUILD_DOCUMENTATION=OFF
        -DPCRE2CPP_ENABLE_CLANG_TIDY=OFF
        -DPCRE2CPP_ENABLE_CXX20=ON
        -DPCRE2CPP_DISABLE_ASSERT_ON_RELEASE=ON
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(CONFIG_PATH cmake)

file(REMOVE_RECURSE
    "${CURRENT_PACKAGES_DIR}/debug"
    "${CURRENT_PACKAGES_DIR}/lib"
)

vcpkg_install_copyright(FILE_LIST
    "${SOURCE_PATH}/LICENSE"
    "${SOURCE_PATH}/LICENSE_PCRE2"
)

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
